stratisproject/FederatedSidechains

- src/FedKeyPairGen/FedKeyPairGen.csproj
- src/Stratis.FederatedPeg.Features.FederationGateway/Stratis.FederatedPeg.Features.FederationGateway.csproj
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
- src/Stratis.FederatedSidechains.Initialisation.Tests/Stratis.FederatedSidechains.Initialisation.Tests.csproj
- src/Stratis.FederatedSidechains.Initialisation/Stratis.FederatedSidechains.Initialisation.csproj
- src/Stratis.FederatedSidechains.IntegrationTests/Stratis.FederatedSidechains.IntegrationTests.csproj
- src/Stratis.FederationGatewayD/Stratis.FederationGatewayD.csproj
- src/Stratis.SidechainD/Stratis.SidechainD.csproj
- src/Stratis.Sidechains.Networks/Stratis.Sidechains.Networks.csproj
needed for code coverage analysis
> make sure all projects are in full debug mode

- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IOpReturnDataReader.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/MonitorChain/CrossChainTransactionMonitor.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/MonitorChain/OpReturnDataReader.cs
- src/Stratis.FederatedPeg.Tests/OpReturnDataReaderTests.cs
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
Added an interface and some tests
> OpReturnDataReader

- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/RestBlockTipSender.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/RestMaturedBlockSender.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/RestSenderBase.cs
As it was causing problems constructing the related classes at start-up.
This was related to #150.
> Removed string parameter from constructor.

- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
it conflicts with the FullNode Api
> we can't use services.AddHttpClient from Microsoft.Extensions.Http

- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
Fixes a bug in the synchronization and adds a test case.
> Add test case to Synchronization

- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewaySettings.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/ICrossChainTransfer.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/ICrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IFederationGatewaySettings.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransfer.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/StatusChangeTracker.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/WithdrawalExtractor.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletTransactionHandler.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/TransactionData.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
- src/Stratis.FederatedPeg.Tests/WithdrawalExtractorTests.cs
This closes #137, closes #100, closes #135, and closes #119.
> Finialize CrossChainStore initial test cases and refactoring

- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/ICrossChainTransfer.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/ICrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IFederationWalletManager.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransfer.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletManager.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
Closes https://github.com/stratisproject/FederatedSidechains/issues/184
> Add `Suspended` status to store

- src/Stratis.FederationGatewayD/Program.cs
my bad the gateway wouldn't start otherwise
I am still trying to get the POA to advance :/
> fix-dependency-injection-issue

- src/Stratis.FederatedPeg.IntegrationTests/Stratis.FederatedPeg.IntegrationTests.csproj
- src/Stratis.FederatedPeg.IntegrationTests/Utils/PowerShellScriptGeneratorAsTests.cs
- src/Stratis.FederatedPeg.IntegrationTests/Utils/SidechainNodeBuilder.cs
- src/Stratis.FederatedPeg.IntegrationTests/Utils/SidechainNodeRunner.cs
(where the premine goes to multisig)
> add runner special for sidechain network

- src/FedKeyPairGen/FederationSetup.csproj
- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/ICrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Notifications/BlockObserver.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/RestBlockTipSender.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/RestMaturedBlockSender.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/RestSenderBase.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Stratis.FederatedPeg.Features.FederationGateway.csproj
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/EventsPersister.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/RestMaturedBlockRequester.cs
- src/Stratis.FederatedPeg.IntegrationTests/Stratis.FederatedPeg.IntegrationTests.csproj
- src/Stratis.FederatedPeg.IntegrationTests/Utils/SidechainNodeRunner.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
- src/Stratis.FederatedPeg.Tests/EventsPersisterTests.cs
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
- src/Stratis.FederationGatewayD/Stratis.FederationGatewayD.csproj
- src/Stratis.SidechainD/Stratis.SidechainD.csproj
- src/Stratis.Sidechains.Networks/Stratis.Sidechains.Networks.csproj
> Add locks and check that the federated wallet manager dealt with any forks

- src/FedKeyPairGen/FederationSetup.cs
- src/FedKeyPairGen/Program.cs
Changed the console app to have a menu rather than being a command line tool.
The reason for that is that this utility is to be used by federation members and this change makes that easier.
Also changed it so that it loops until the user exits
> Adapted the console app to have a menu

- src/FedKeyPairGen/FederationSetup.cs
- src/FedKeyPairGen/Program.cs
* Made Network non-optional
* Added text option to genesis block
* Generate pubkeys properly, with file for migning priv key.
> Federation Setup tool - small improvements

- src/FedKeyPairGen/GenesisMiner.cs
- src/FedKeyPairGen/Program.cs
- src/Stratis.FederatedPeg.IntegrationTests/Utils/PowerShellScriptGeneratorAsTests.cs
- src/Stratis.Sidechains.Networks/FederatedPegMain.cs
- src/Stratis.Sidechains.Networks/FederatedPegNetwork.cs
- src/Stratis.Sidechains.Networks/FederatedPegRegTest.cs
- src/Stratis.Sidechains.Networks/FederatedPegTest.cs
Made a few changes here to generate a genesis block for the FederatedPegTest.
> Setup of  FederatedPegTest

- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/ICrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IFederationWalletManager.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/PartialTransactionRequester.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletManager.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTestBase.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
This PR adds code to improve stability, recovery and fault tolerance.
> Improve stability and fault tolerance

- src/Stratis.FederatedPeg.Features.FederationGateway/FederatedPegBlockDefinition.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.IntegrationTests/Utils/PowerShellScriptGeneratorAsTests.cs
The address at which the premine is supposed to be sent was wrongly calculated.
in the Build() method, the tip is the current tip so it's behind the block being mined.
> Fix the Build index

- src/FedKeyPairGen/FederationSetup.csproj
- src/Stratis.FederatedPeg.Features.FederationGateway/Stratis.FederatedPeg.Features.FederationGateway.csproj
- src/Stratis.FederatedPeg.IntegrationTests/LeaderTests.cs
- src/Stratis.FederatedPeg.IntegrationTests/Stratis.FederatedPeg.IntegrationTests.csproj
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
- src/Stratis.FederationGatewayD/Stratis.FederationGatewayD.csproj
- src/Stratis.SidechainD/Stratis.SidechainD.csproj
- src/Stratis.Sidechains.Networks/Stratis.Sidechains.Networks.csproj
- src/nuget.config
This will build as soon as the release goes out :)
1.2.7-beta => 3.0.0.0
4.0.0.70 => 4.0.0.71
> upgrade to release version of FullNode

- src/FedKeyPairGen/GenesisMiner.cs
- src/FedKeyPairGen/MultisigAddressCreator.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Controllers/FederationWalletController.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewaySettings.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Notifications/BlockObserver.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/PartialTransactionsBehavior.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/MaturedBlocksProvider.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransfer.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/EventsPersister.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/RestMaturedBlockRequester.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWallet.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletManager.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletSyncManager.cs
- src/Stratis.FederatedPeg.IntegrationTests/MiningTests.cs
- src/Stratis.FederatedPeg.IntegrationTests/Utils/SidechainNodeBuilder.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTestBase.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
- src/Stratis.FederatedPeg.Tests/FederationGatewayControllerTests.cs
- src/Stratis.FederatedSidechains.AdminDashboard/Controllers/HomeController.cs
- src/Stratis.FederatedSidechains.AdminDashboard/Services/FetchingBackgroundService.cs
- src/Stratis.SidechainD/Program.cs
- src/Stratis.Sidechains.Networks/FederatedPegRegTest.cs
Quick PR to fix some of the codestyle violations
> Fixing codestyle issues

- src/FedKeyPairGen/FederationSetup.csproj
- src/Stratis.FederatedPeg.Features.FederationGateway/FederatedPegBlockDefinition.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Stratis.FederatedPeg.Features.FederationGateway.csproj
- src/Stratis.FederatedPeg.IntegrationTests/Stratis.FederatedPeg.IntegrationTests.csproj
- src/Stratis.FederatedPeg.IntegrationTests/Utils/PowerShellScriptGeneratorAsTests.cs
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
- src/Stratis.FederationGatewayD/Stratis.FederationGatewayD.csproj
- src/Stratis.SidechainD/Stratis.SidechainD.csproj
- src/Stratis.SidechainDnsD/Stratis.SidechainDnsD.csproj
- src/Stratis.Sidechains.Networks/Stratis.Sidechains.Networks.csproj
also add --no-build back to the script
> package upgrade to 3.0.0.0 to 3.0.0.1

- src/Stratis.FederationGatewayD/Program.cs
Moved common features between side and main chains to extension to reduce code duplication and so we can visually see how those 2 nodes differ- which features are common and which are different between the two
> Moved common features between side and main chains to extension

- src/Stratis.SidechainDnsD/Program.cs
actually removed just RPC
we have still to remove Wallet and Mining features but actually consensus requires a service registered by mining feature, and wallet is required by mining feature... so can't remove them until we fix that problems
> removed RPC feature

- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/ICrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
implementation of issue #269
I created an helper method to format the console output. I'd like to create an helper/class to handle those kind of stuffs and put it on SBFN, actually our console outputting part is too much verbose and chaotic
> Benchmark for NodeStore component

- src/Stratis.FederatedPeg.Features.FederationGateway/Controllers/FederationGatewayController.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Models/FederationGatewayInfoModel.cs
- src/Stratis.FederatedPeg.Tests/FederationGatewayControllerTests.cs
Added a very useful endpoint that helps knowing how the federation is set up.
Useful for the dashboard and the test tool.
> Add GetInfo API endpoint

- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IFederationWalletManager.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IWithdrawal.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/Withdrawal.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletManager.cs
Shows information relating to recent withdrawals in the console.
> Display recent withdrawal information to console

- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/EventsPersister.cs
> Prevent duplicate block requests

- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
Logs that are needed to investigate other issues
> Logging and codestyle

- src/FedKeyPairGen/FederationSetup.csproj
- src/Stratis.FederatedPeg.Features.FederationGateway/Stratis.FederatedPeg.Features.FederationGateway.csproj
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.IntegrationTests/NodeSetupTests.cs
- src/Stratis.FederatedPeg.IntegrationTests/Stratis.FederatedPeg.IntegrationTests.csproj
- src/Stratis.FederatedPeg.IntegrationTests/Utils/SidechainTestContext.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTestBase.cs
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
- src/Stratis.FederationGatewayD/Stratis.FederationGatewayD.csproj
- src/Stratis.SidechainD/Stratis.SidechainD.csproj
- src/Stratis.SidechainDnsD/Stratis.SidechainDnsD.csproj
- src/Stratis.Sidechains.Networks/Stratis.Sidechains.Networks.csproj
Goes in after #309.
Sets up 2 chains. 
Mines coins on main chain.
Sends to sidechain via federation.
Verifies that coins are received on sidechain.
Much to expand on from here.
> Cross-chain transfer integration test in C#.

- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/ICrossChainTransfer.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransfer.cs
> Add Signature Counts to Console

- src/Stratis.FederatedPeg.IntegrationTests/Resources/HelperMethods.PS1
- src/Stratis.FederatedPeg.IntegrationTests/Stratis.FederatedPeg.IntegrationTests.csproj
- src/Stratis.FederatedPeg.IntegrationTests/Utils/PowerShellScriptGeneratorAsTests.cs
To be able to update easier the generation of the dashboard in case we want to improve it, I've included an embedded ps1 in the project that will be loaded by the generation test
> Implemented the generation of the debugging dashboard for ps1 script

- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletTransactionHandler.cs
This is copied from what we have in the SBFN.
Also removed the unused `CoinType coinType`.
> Make sure that the minimum fee is respected

- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransfer.cs
Fixes the "fix" on PR https://github.com/stratisproject/FederatedSidechains/pull/317. ;)
> Fix signature count

- src/FedKeyPairGen/GenesisMiner.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/NetworkHelpers/NetworkExtensions.cs
- src/Stratis.Sidechains.Networks/FederatedPegMain.cs
- src/Stratis.Sidechains.Networks/FederatedPegNetwork.cs
- src/Stratis.Sidechains.Networks/FederatedPegRegTest.cs
- src/Stratis.Sidechains.Networks/FederatedPegTest.cs
Still waiting for a name so that we can updae it and change the tocker etc.
This can be reviewed commit by commit.
> FedPegMain definition

- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
> small fix for 323

- src/FederatedPeg.sln
- src/Stratis.FederatedPeg.IntegrationTests.Tools/Stratis.FederatedPeg.IntegrationTests.Tools.csproj
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
- src/XUnitRetry/DelayedMessageBus.cs
- src/XUnitRetry/RetryAttribute.cs
- src/XUnitRetry/RetryFactDiscoverer.cs
- src/XUnitRetry/RetryTestCase.cs
- src/XUnitRetry/XUnitRetry.csproj
nuget package only exists for net451
> Change Xunit Retry reference

- src/Stratis.SidechainD/Stratis.SidechainD.csproj
- src/Stratis.SidechainDnsD/Stratis.SidechainDnsD.csproj
- src/Stratis.Sidechains.Networks/Stratis.Sidechains.Networks.csproj
The MainChain_To_SideChain test is being a bit sporadic for me, but it has been passing.
> NuGet version updates
