stratisproject/FederatedSidechains

- src/FedKeyPairGen/FedKeyPairGen.csproj
- src/FederatedPeg.sln
- src/Stratis.FederatedPeg.Features.FederationGateway/Stratis.FederatedPeg.Features.FederationGateway.csproj
- src/Stratis.FederatedPeg.Tests/IPEndPointComparerTests.cs
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
- src/Stratis.FederatedSidechains.Initialisation.Tests/Stratis.FederatedSidechains.Initialisation.Tests.csproj
- src/Stratis.FederatedSidechains.IntegrationTests/Stratis.FederatedSidechains.IntegrationTests.csproj
- src/Stratis.FederationGatewayD/Stratis.FederationGatewayD.csproj
- src/Stratis.SidechainD/Stratis.SidechainD.csproj
- src/Stratis.Sidechains.Networks/ApexMain.cs
- src/Stratis.Sidechains.Networks/ApexRegTest.cs
- src/Stratis.Sidechains.Networks/ApexTest.cs
- src/Stratis.Sidechains.Networks/Stratis.Sidechains.Networks.csproj
Stratis.Bitcoin.* 1.2.3-beta
NStratis 4.0.0.67
Microsoft.NET.Test.Sdk 15.9.0
Xunit 2.4.1
That meant removing unused Integration test project which used corrupted Stratis.Bitcoin.IntegrationTests.Common temporarily
> upgrades libraries

- requirements/cross-chain-transfer.md
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletManager.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletTransactionHandler.cs
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
- src/Stratis.FederatedPeg.Tests/TransactionBuilderTests.cs
Resolves #108.
Some notes about the implementation:
- For purposes of deterministic ordering of input UTXO's they are ordered by transactions id and NOT by the position of the transaction within the block they occur in. This means that the ordering mainly by block age.
- Default output order has been retained.
> Deterministic creation of target transactions

- .gitignore
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletManager.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
- src/Stratis.FederatedPeg.Tests/TransactionBuilderTests.cs
Relates to #137 
- On restart we have to check that our transaction's UTXO's are still valid.
- Once ProcessTransaction has been called we want to check that UTXO's are not re-used.
> Add sanity check to sync between store and wallet

- src/nuget.config
powershell-core is not used any more, so it gets replaced
> new nuget source

- src/Stratis.FederatedPeg.IntegrationTests/Utils/PowerShellScriptGeneratorAsTests.cs
Missing $ sign.  Causing the script to fail.
> Missing $ sign in PowerShellScriptGeneratorAsTests

- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/DepositExtractor.cs
- src/Stratis.FederatedPeg.Tests/DepositExtractorTests.cs
Changes the initialisation of `this.depositScript` from:
```
this.depositScript = federationGatewaySettings.MultiSigRedeemScript;
```
to
```
// Note: MultiSigRedeemScript.PaymentScript equals MultiSigAddress.ScriptPubKey
this.depositScript =
federationGatewaySettings?.MultiSigRedeemScript?.PaymentScript ??
federationGatewaySettings?.MultiSigAddress?.ScriptPubKey;
```
to fix the issue where deposits are not being extracted.
> Fix deposit extractor

- src/Stratis.FederatedPeg.IntegrationTests/Utils/PowerShellScriptGeneratorAsTests.cs
Give federation nodes enough time to start, before calling any WebAPI requests against the nodes.
> Increase federation nodes time to load - to stop WebAPI requests from failing.

- src/Stratis.FederatedPeg.Features.FederationGateway/FederatedPegBlockDefinition.cs
- src/Stratis.FederatedPeg.IntegrationTests/Utils/PowerShellScriptGeneratorAsTests.cs
- src/Stratis.Sidechains.Networks/FederatedPegRegTest.cs
The important change is in FederatedPegBlockDefinition.cs.
We were calling the BlockDefiniton's Onbuild method directly rather than the smartContract's one.
Changed RegTest so that it can be used with StratisTest and the local powershell script.
> Fix the block definition for SmartContracts

- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewaySettings.cs
FederationNodeIpEndPoints will be null if no federation node IPs are passed in, causing an `PartialTransactionsBehavior.AttachCore` to throw an exception.
> Add default collection if federationips param is not set

- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IEventPersister.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IFederationWalletManager.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/PartialTransactionsBehavior.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/EventsPersister.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletManager.cs
This PR gets the cross-chain transfers to run non-stop.
After these changes I was able to process the following 5 deposits found on Stratis Testnet without stopping (list of deposit ids): EB28..., 5387..., FAA0..., 72B2... and 171F... Corresponding block heights: 667197, 667311, 667361, 668602 and 668620. Deposit amounts: 1.0, 1.1, 3.14, 23.0 and 15.0.
Goals of this PR:
- Remove unnecessary transactionId parameter  from FindWithdrawalTransactions.
- Moved code outside of the lock to inside the lock and also added logic to check if a withdrawal  
transaction is already present in the wallet (keyed by depositId).
- Update ValidateCrossChainTransfer to identify wallet transactions by deposit id vs transaction id.
Adopts the wallet transaction if present and sets  an appropriate status.
- …
> Running non-stop

- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IOpReturnDataReader.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/OpReturnDataReader.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/DepositExtractor.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/WithdrawalExtractor.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
- src/Stratis.FederatedPeg.Tests/DepositExtractorTests.cs
- src/Stratis.FederatedPeg.Tests/OpReturnDataReaderTests.cs
- src/Stratis.FederatedPeg.Tests/WithdrawalExtractorTests.cs
All methods that start with `Try` should return bool that will tell caller was it a success or fail and an out param with the value if it was success
> fix methods in opreturn reader

- src/Stratis.FederationGatewayD/Program.cs
Was getting this a lot on the mainchain federation nodes:
```
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
Peer '[::ffff:13.64.76.48]:26178' offline, reason: 'The peer does not support the required services requirement, reason: peer version is too low'.
```
> Explicitly specify minimum protocol versions

- src/FedKeyPairGen/FederationSetup.csproj
- src/Stratis.FederatedPeg.Features.FederationGateway/Stratis.FederatedPeg.Features.FederationGateway.csproj
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.IntegrationTests/Stratis.FederatedPeg.IntegrationTests.csproj
- src/Stratis.FederatedPeg.Tests/CrossChainTestBase.cs
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
- src/Stratis.FederationGatewayD/Stratis.FederationGatewayD.csproj
- src/Stratis.SidechainD/Stratis.SidechainD.csproj
- src/Stratis.SidechainDnsD/Stratis.SidechainDnsD.csproj
- src/Stratis.Sidechains.Networks/Stratis.Sidechains.Networks.csproj
Allows the sidechains repo to serialize everything given the changes to the FN Dbreeze serialization and ultimately allows multiple nodes to run in the one process by removing static dependencies.
I haven't actually connected to the network and completed a transfer yet - if someone could do that it would be ace.
> NuGet update and Dbreeze serialization fix

- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/WithdrawalExtractor.cs
Fixes the following:
- Call to `GetMoreBlocksAsync` from `FederationGatewayFeature`. These calls should only happen when the mainchain sends the sidechain a matured block that is ahead of the next expected matured block OR when the sidechain want to expedite matters by immediately requesting more blocks following the processing of a batch of blocks.
- An if statement with commented code that should have been removed completely.
- Removal of wallet transactions associated with suspended transfers.
- Invalid script addresses being displayed in console.
> Fix a few small issues

- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletSyncManager.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTestBase.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
Changes as follows:
- Added a network argument to the test class constructor and added a new test class for Stratis that simply derives from the previous test class. This automatically inherits the test cases.
- Made changes to the tests and supporting methods to support cloning chains. Previously we relied on deterministic chain creation.
- Removed a superfluous test case as we are restoring from the chain in each test case anyway.
- Changed arbitrary number of blocks added after funding to instead use `MinCoinMaturity`.
> Make tests currently running against FedPeg network run against Stratis too

- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletManager.cs
Removes the unused `MultiSigInput` method.
> Remove unused method from FederationWalletManager

- src/Stratis.FederatedPeg.Features.FederationGateway/LeaderProvider.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Notifications/BlockObserver.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/RestClients/FederationGatewayClient.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/RestClients/RestApiClientBase.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/MaturedBlocksSyncManager.cs
- src/Stratis.FederatedPeg.IntegrationTests/NodeSetupTests.cs
- src/Stratis.FederatedPeg.Tests/BlockObserverTests.cs
- src/Stratis.FederatedPeg.Tests/MaturedBlocksSyncManagerTests.cs
- src/Stratis.FederatedPeg.Tests/RestClientsTests/RestApiClientBaseTests.cs
- src/Stratis.FederatedPeg.Tests/Stratis.FederatedPeg.Tests.csproj
Added cancellation to REST API client. 
Removed blocking call from OnNextCore callback
Fix: #310
> Fix for: Polly prevents node syncing when counter chain API isn't available.

- src/Stratis.FederatedPeg.Features.FederationGateway/Controllers/FederationWalletController.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IFederationWalletManager.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Models/RequestModels.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Wallet/FederationWalletManager.cs
- src/Stratis.FederatedPeg.IntegrationTests/Utils/SidechainTestContext.cs
- src/Stratis.FederatedPeg.Tests/CrossChainTestBase.cs
The IsFederationActive call takes 961 ms (almost a full second). 
This PR adds a cache of parameters / result values.
> Cache results of IsFederationActive (961ms)

- src/Stratis.FederatedPeg.Features.FederationGateway/RestClients/FederationGatewayClient.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/RestClients/RestApiClientBase.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/SourceChain/MaturedBlocksProvider.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/MaturedBlocksSyncManager.cs
- src/Stratis.FederatedPeg.Tests/RestClientsTests/FederationGatewayClientTests.cs
- src/Stratis.FederatedPeg.Tests/Utils/TestingHttpClient.cs
This reverts https://github.com/stratisproject/FederatedSidechains/pull/334
Since I think that PR fixes consequence instead of source of the problem. Source of the problem is the generation of duplicated requests by another gateway. 
Instead of cache I've added 60s timeout, made sure blocks collection takes no more than around 30s, reduced max batch size from 1000 to 100.
> Removed cache from MaturedBlocksProvider and reduced batch side, added 60s timeout

- src/Stratis.FederatedPeg.Features.FederationGateway/Controllers/FederationWalletController.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/FederationGatewayFeature.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Interfaces/IWithdrawalHistoryProvider.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/Models/WithdrawalModel.cs
- src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/WithdrawalHistoryProvider.cs
This PR makes the warning a bit more visible, fixes extraneous indentation and removes unnecessary '===...' in the code.
> Clean up warning and associated code-style
